### ISSUE TITLE
Enemies dosen't bounce of correctly

### ISSUE THREAD

**Issue by Cilivarus** [Zalmez/Zal-CiliPractice#8]
**Enemies:**
- Doesn't bounce properly to assigned window.
  They will hit an invisible wall to the right, and disappear before bouncing back from the bottom window.
- "SeekerEnemy" (Green Enemy) teleports to the left corner when turning left.
   This should not happen, as the enemy is supposed to follow the player slowly. (Anti-AFK enemy)

**Comment by Zalmez** [comment]
@Cilivarus status?

**Comment by Cilivarus** [comment]
Har fikset bugsene i spillet nå. Så langt er det bug-free 💃 💃

**Comment by Zalmez** [comment]
close #8
